# Site settings
baseURL = "https://enzu.ru"
languageCode = "en-US"
title = "enzu.ru"
theme = "split"
disableKinds = ["section", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2025 enzu.ru"

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "A. Khanzada"
  description = "enzu.ru"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Whether you purchased the license from the author.
  licensed = false

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/srs.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Code"

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/enzuru"
        new_tab = true

      [[params.links.list1.link]]
        text = "GitLab"
        url = "https://gitlab.gnome.org/enzuru"
        new_tab = true

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Links"

      [[params.links.list2.link]]
        text = "Medium"
        url = "https://enzuru.medium.com"
        new_tab = true

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/ahmed-khanzada/"
        new_tab = true

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Contact"

      [[params.links.list3.link]]
        text = "Email"
        url = "mailto:enzuru@me.com"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
