copyright = "Â© Ahmed Khanzada"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Los_Angeles"
timeout = "120s"
title = "enzu.ru"

[params]
  defaultTheme = "dark"
  description = "Ahmed Khanzada's porfolio"
  title = "enzu.ru"
  [params.author]
    email = "enzuru@me.com"
    name = "Ahmed Khanzada"
  [params.socialIcons]
    github = "https://github.com/enzuru"
    website = "https://medium.com/@enzuru"
    youtube = "https://www.youtube.com/@lenzuru"
    linkedin = "https://www.linkedin.com/in/ahmed-khanzada/"
    email = "mailto:enzuru@me.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "./gallery"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100
