name: Upload to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify --buildDrafts
    # - uses: shallwefootball/s3-upload-action@master
    #   with:
    #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
    #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    #     aws_bucket: ${{ secrets.AWS_BUCKET }}
    #     source_dir: 'public'
    #     destination_dir: "./"
    - uses: Noelware/s3-action@2
      with:
          directories: |
              ./public
          access-key-id: ${{ secrets.AWS_KEY_ID }}
          path-format: '/$(file)'
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          endpoint: https://s3.amazonaws.com
          region: us-east-1
          bucket: ${{ secrets.AWS_BUCKET }}
